apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
    matchLabels:
      app: react
  replicas: 2

  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: taskmanager-react
          image: taskmanager-react:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://"